accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

    path('baby_profile/', views.baby_profile, name='baby_profile'),
    path('edit_baby_profile/edit/', views.edit_baby_profile, name='edit_baby_profile'),
]

album/urls.py
from django.urls import path
from . import views
from album.views import (
    PostDetailView,
    CalendarView,
    ImageDetailView,
)
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('test/', views.test, name='test'),

    path('like/<str:operation>/', views.like, name='like'),
    path('crop_upload/', views.crop_upload, name='crop_upload'),
    path('calendar/new/<str:date>/', views.calendar_new, name='calendar_new'),

    path('', login_required(CalendarView.as_view()), name='home'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),

    path('image/<int:post_pk>/<int:pk>/', login_required(ImageDetailView.as_view()), name='image_detail'),
    path('image/<int:pk>/edit/', views.image_edit, name='image_edit'),
    path('image/<str:operation>/<int:pk>/remove/', views.image_remove, name='image_remove'),
    path('image_comment/<int:pk>/remove/', views.image_comment_remove, name='image_comment_remove'),

    # notification
    path('notification/<str:operation>/<int:pk>/', views.notification, name='notification'),
    # friend
    path('connect/<str:operation>/<int:pk>/', views.change_friends, name='change_friends'),


    # Calendar album page
    path('calendar_view/', views.calendar_view, name='calendar_view'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
# from album.views import CalendarView

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('admin/', admin.site.urls),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('album/', include(('album.urls', 'album'), namespace='album')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager ## A new class is imported. ##
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import Resize

# Extending the base User manager that Django uses for its original UserManager.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    # Defining the same 3 methods that the original Django UserManager has.
    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    # make first_name as case insenditive
    def filter(self, **kwargs):
        if 'first_name' in kwargs:
            kwargs['first_name__iexact'] = kwargs['first_name']
            del kwargs['first_name']
        return super(UserManager, self).filter(**kwargs)

    def get(self, **kwargs):
        if 'first_name' in kwargs:
            kwargs['first_name__iexact'] = kwargs['first_name']
            del kwargs['first_name']
        return super(UserManager, self).get(**kwargs)


# Extending the base class that Django has for User models.
class User(AbstractUser):
    """User model."""

    # Removing the username field.
    username = None
    # Making the email, first_name field required and unique.
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), unique=True, max_length=20)

    # Telling Django that you are going to use the email field as the USERNAME_FIELD.
    USERNAME_FIELD = 'email'
    # Removing the email field from the REQUIRED_FIELDS settings (it is automatically included as USERNAME_FIELD).
    REQUIRED_FIELDS = []
    # Assigning the new Manager to the User model.
    objects = UserManager()


class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Sodra Sandby')


class UserProfile(models.Model):
    # From Django 2.0 on_delete is required
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(blank=True, max_length=100, default='')
    city = models.CharField(blank=True, max_length=100, default='')
    website = models.URLField(blank=True, default='')
    phone = models.CharField(blank=True, max_length=20, default='')
    image = models.ImageField(upload_to='profile_image', blank=True, default='profile_image/flower.png')
    image_thumbnail = ImageSpecField(
		source = 'image',
		processors = [Resize(700, 700)], # 처리할 작업 목룍
		format = 'JPEG',					# 최종 저장 포맷
		options = {'quality': 60})  		# 저장 옵션

    # Sodra_Sandby가 도시인 유저만 보이게 하고싶을때
    # Sodra_Sandby = UserProfileManager()
    objects = models.Manager()

    # user.userprofile 리턴값을 이름으로
    def __str__(self):
        return self.user.email

# User가 생성되면 UserProfile을 생성
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=settings.AUTH_USER_MODEL)

class BabyProfile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=20)
    born_weight = models.IntegerField(default=0)
    born_height = models.IntegerField(default=0)
    born_location = models.CharField(max_length=20, blank=True)
    birthday = models.DateTimeField()
    image = models.ImageField(upload_to='baby_profile_image', blank=True, default='profile_image/flower.png')
    image_thumbnail = ImageSpecField(
		source = 'image',
		processors = [Resize(700, 700)], # 처리할 작업 목룍
		format = 'JPEG',					# 최종 저장 포맷
		options = {'quality': 60})  		# 저장 옵션

    def __str__(self):
        return str(self.first_name)+str(self.last_name)

class Milestone(models.Model):
    milestone = models.CharField(max_length=30)
    date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=50)

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile, BabyProfile, Milestone
from accounts.models import User
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput

# class EntryForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     date = forms.DateTimeField()
#     description = forms.CharField(widget=forms.Textarea)

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'email',
            'password1',
            'password2',
        )
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.is_active = False

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'password',
            'first_name',
            'last_name',
        )

class UserProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'description',
            'city',
            'website',
            'phone',
            'image',
        )

class BabyForm(forms.ModelForm):
    birthday = forms.SplitDateTimeField()
    class Meta:
        model = BabyProfile
        fields = (
            'image',
            'first_name',
            'last_name',
            'birthday',
            'born_weight',
            'born_height',
            'born_location',
        )
    def __init__(self, *args, **kwargs):
        super(BabyForm, self).__init__(*args, **kwargs)
        self.fields['birthday'].widget.widgets[0]=DatePickerInput(format='%Y-%m-%d')
        self.fields['birthday'].widget.widgets[1]=TimePickerInput(format='%H:%M')

class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestone
        fields = (
            'milestone',
            'date',
            'description',
        )

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.http import HttpResponseRedirect
from django.contrib import messages
from accounts.models import User
from .models import UserProfile, BabyProfile
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from album.models import Calendar, Friend
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .forms import (
    # EntryForm,
    RegistrationForm,
    EditProfileForm,
    UserProfileImageForm,
    BabyForm,
    MilestoneForm
)

def baby_profile(request):
    baby = BabyProfile.objects.get(first_name='Angelica Teresa Hyeyeong')
    today = datetime.now().date()

    posts = []
    newyear_post = Calendar.objects.filter(date__month='1', date__day='1').order_by('date').last()
    posts.append(newyear_post)

    christmas_post = Calendar.objects.filter(date__month='12', date__day='25').order_by('date').last()
    posts.append(christmas_post)

    if request.method == "POST":
        form = MilestoneForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            if 'image' in request.FILES:
                print('--------------milestone test-----------------')
            form.save()
            return redirect('accounts:baby_profile')
    else:
        form = MilestoneForm()

    args = {
        'baby': baby,
        'posts': posts,
        'today': today,
        'form': form,
    }
    return render(request, 'accounts/baby_profile.html', args)

@login_required
def edit_baby_profile(request):
    baby = get_object_or_404(BabyProfile, first_name='Angelica Teresa Hyeyeong')
    if request.user.is_superuser:
        if request.method == "POST":
            form = BabyForm(request.POST, instance=baby)
            if form.is_valid():
                baby = form.save(commit=False)
                if 'image' in request.FILES:
                    baby.image.delete()
                    baby.image = request.FILES['image']
                baby.save()
                return redirect('accounts:baby_profile')
        else:
            form = BabyForm(instance=baby)
        args = {
            'form': form,
        }
        return render(request, 'accounts/edit_baby_profile.html', args)
    else:
        return redirect('album:home')


def welcome(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            ######### this makes users automatically log in when they successfully register
            # email = form.cleaned_data['email']
            # password = form.cleaned_data['password1']
            # user = authenticate(email=email, password=password)
            # login(request, user)
            ##########
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()


    args = {'form': form}
    return render(request, 'welcome.html', args)

def user_login(request):
    if request.method == 'GET':
        context = ''
        return render(request, 'registration/login.html', {'context': context})

    elif request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        # setting.py -> AUTHENTICATION_BACKENDS -> allow inactive users to login
        user = authenticate(request, email=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('album:home'))
            else:
                context = 'Your account is not activated yet. Please contact Gwangyeong to activate your account.'  # to display error?
                return render(request, 'registration/login.html', {'context': context})
        else:
            context = 'Please enter a correct email and password. Note that both fields may be case-sensitive.'   # to display error?
            return render(request, 'registration/login.html', {'context': context})

@login_required
def view_profile(request, pk=None):
    if pk:
        user_pk = User.objects.get(pk=pk)
    else:
        user_pk = request.user

    users = User.objects.exclude(id=request.user.id)
    # friend = Friend.objects.get(current_user=request.user) => need to create
    friend, created = Friend.objects.get_or_create(current_user=request.user)
    friends = friend.users.all()

    args = {
        'user': user_pk,
        'users': users,
        'friends': friends,
    }
    return render(request, 'accounts/profile.html', args)

@login_required
def edit_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        edit_profile_form = EditProfileForm(request.POST, instance=request.user)
        user_profile_image_form = UserProfileImageForm(request.POST, request.FILES, instance=user_profile)

        if edit_profile_form.is_valid() and user_profile_image_form.is_valid():
            user = edit_profile_form.save()
            image = user_profile_image_form.save(commit=False)
            image.user = user

            if 'image' in request.FILES:

                image.image = request.FILES['image']

            image.save()
            return redirect(reverse('accounts:view_profile'))

        else:
            print(edit_profile_form.errors, user_profile_image_form.errors)
    else:
        edit_profile_form = EditProfileForm(instance=request.user)
        user_profile_image_form = UserProfileImageForm(instance=user_profile)

    args = {'edit_profile_form': edit_profile_form, 'user_profile_image_form': user_profile_image_form}
    return render(request, 'accounts/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, "Password has been successfully changed.")
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
    else:
        form = PasswordChangeForm(user=request.user)

    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/baby_profile.html
{% extends 'base.html' %}
{% load custom_tags %}
{% block extrahead %}


{% endblock %}
{% block content %}

<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    </form>
    <hr>
    {% if request.user.is_superuser %}
    <button onclick="window.location='{% url 'accounts:edit_baby_profile' %}'" class="btn btn-primary">Edit</button>
    <hr>
    {% endif %}

    <div class="bg-transparent">
        <div class="text-center">
            <h2 class="font-weight-bold text-secondary">{{baby.first_name}}</h2>
            <h2 class="font-weight-bold text-secondary">{{baby.last_name}}</h2>
            <a href="{{ baby.image.url }}">
                <img class="img-circle" src="{{ baby.image_thumbnail.url }}" width="240"/>
            </a>
        </div>
        <div class="row text-center pt-3">
            <div class="col-3">
                <i class="fas fa-weight text-primary" style="font-size:35px;"></i>
                <br>
                {{baby.born_weight}}g
            </div>
            <div class="col-3">
                <i class="fas fa-ruler-combined text-primary" style="font-size:35px;"></i>
                <br>
                {{baby.born_height}}cm
            </div>
            <div class="col-3">
                <i class="fas fa-birthday-cake text-primary" style="font-size:35px;"></i>
                <br>
                {{baby.birthday|date:"Y-m-d P"}}
            </div>
            <div class="col-3">
                <i class="fas fa-thumbtack text-primary" style="font-size:35px;"></i>
                <br>
                {{baby.born_location}}
            </div>
        </div>
        <hr>

        <div class="card">
            <ul class="nav nav-pills text-center" id="pills-tab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="development-tab" data-toggle="pill" href="#development" role="tab" aria-controls="development" aria-selected="true">
                        Development
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="Milestones-tab" data-toggle="pill" href="#Milestones" role="tab" aria-controls="Milestones" aria-selected="false">
                        Milestones
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="growth-tab" data-toggle="pill" href="#growth" role="tab" aria-controls="growth" aria-selected="false">
                        growth
                    </a>
                </li>
            </ul>
            <hr class="mt-0">
            <div class="tab-content" id="pills-tabContent">
                <div class="tab-pane fade show active" id="development" role="tabpanel" aria-labelledby="development-tab">
                    <h3 class="text-center">Second Month</h3>
                    <hr>
                    <div class="bd-example bd-example-tabs">
                        <div class="row">
                            <div class="col-4">
                                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                                    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">
                                        Motor Skills
                                    </a>
                                    <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">
                                        Profile
                                    </a>
                                    <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
                                        Messages
                                    </a>
                                    <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">
                                        Settings
                                    </a>
                                </div>
                            </div>
                            <div class="col-8">
                                <div class="tab-content" id="v-pills-tabContent">
                                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                                        Two-month-old babies are gaining more control over their bodies. That means they can hold their head a little steadier while lying on their tummies or being supported upright.<br>
                                        In the second month of life, babies continue to have a strong sucking reflex. You may notice your baby likes to suck on a fist or a few fingers. This is one of the best ways babies have of comforting themselves.<br>
                                        At 2 months, your baby doesn’t yet have the coordination to play with toys. But she may bat at a colorful object hanging in front of her. Your baby may even briefly hold a toy that you place in one of her hands.
                                    </div>
                                    <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                                        1-2
                                    </div>
                                    <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
                                        1-3
                                    </div>
                                    <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
                                        1-4
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="Milestones" role="tabpanel" aria-labelledby="Milestones-tab">
                    <div class="row">
                        <div class="col-6 col-md-4 col-lg-3">
                            <i class="fas fa-plus text-primary" style="font-size:21px;"></i>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-6 col-md-4 col-lg-3">
                            123
                        </div>
                        <div class="col-6 col-md-4 col-lg-3">
                            123
                        </div>
                        <div class="col-6 col-md-4 col-lg-3">
                            123
                        </div>


                    </div>
                </div>
                <div class="tab-pane fade" id="growth" role="tabpanel" aria-labelledby="growth-tab">
                    3333333
                </div>
            </div>
        </div>





    </div>
    <hr>

    <div class="container-fluid bg-3 text-center">
        <h3>Memories!</h3><br>
        <div class="row text-center">
            {% for post in posts %}
            {% if post.pk %}
            <div id="memory_Carousel" class="carousel slide  text-center mb-3 col-6 col-md-4 col-lg-3" data-ride="carousel">
                <ol class="carousel-indicators">
                    {% if post.images.all|length > 1 %}
                    {% for image in post.images.all %}
                    <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
                    {% endfor %}
                    {% endif %}
                </ol>
                <div class="carousel-inner">
                    {% for image in post.images.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <h6 class="text-primary">< {{ post.date|date:"Y.m.d" }} ></h6>
                        <a class="portfolio-box" href="{% url 'album:image_detail' post_pk=post.pk pk=image.pk  %}">
                                    <img class="img-thumbnail w3-round-xlarge img-responsive" style="width: 100%; display: block;" src="{{ image.thumbnail.url }}" alt="Card image">
                                </a>
                    </div>
                    {% if post.images.all|length != 1 %}
                    <a class="carousel-control-prev" href="#memory_Carousel" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                    <a class="carousel-control-next" href="#memory_Carousel" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    {% endblock %}

accounts/templates/accounts/change_password.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>Change password</h1>
    <hr>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            {{ field.errors }}
            <input type="password" placeholder="{{ field.label }}" name="{{ field.name }}" class="form-control">
            <br>
        {% endfor %}
            <ul>
                <li>Your password can't be too similar to your other personal information.</li>
                <li>Your password must contain at least 8 characters.</li>
                <li>Your password can't be a commonly used password.</li>
                <li>Your password can't be entirely numeric.</li>
            </ul>
        </div>
        <button type="submit" name="button" class="btn btn-primary">Submit</button>
    </form>
</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h3>
    {% if user.first_name %}
        {{ user.first_name }}
    {% else %}
        {{ user }}
    {% endif %}
        's Profile
    </h3>
    <hr>
    <p>Email: {{ user.email }}</p>
    <p>First name: {{ user.first_name }}</p>
    <p>Last name: {{ user.last_name }}</p>
    <p>Description: {{ user.userprofile.description }}</p>
    <p>City: {{ user.userprofile.city }}</p>
    <p>Website: {{ user.userprofile.website }}</p>
    <p>Phone: {{ user.userprofile.phone }}</p>
    {% if user.userprofile.image %}
        <a href="{{ user.userprofile.image.url }}">
            <img class="img-thumbnail" src="{{ user.userprofile.image.url }}" width="240"/> <br>
        </a>
    {% endif %}

    <hr>
    {% if user == request.user %}
    <button onclick="window.location='{% url 'accounts:edit_profile' %}'" class="btn btn-primary my-2">Edit profile</button>
    <button onclick="window.location='{% url 'accounts:change_password' %}'" class="btn btn-primary my-2">Change Password</button>
    <br>
    <div class="col-md-4">
        <h3>Other People</h3>
        {% for user in users %}
            {% if not user in friends %}
            <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                {% if user.first_name %}
                    <h6>{{ user.first_name }}({{ user.email }})</h6>
                {% else %}
                    <h6>{{ user.email }}</h6>
                {% endif %}
            </a>
            {% endif %}
        {% endfor %}
        <h3 class="font-weight-bold">Friends List</h3>
        {% for friend in friends %}
            <div class="media">
                <a href="{{ friend.userprofile.image.url }}">
                    <img class="rounded-circle mr-3" src="{{ friend.userprofile.image_thumbnail.url }}" width="30" height="30"/>
                </a>
                <div class="media-body">
                    <a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
                        {% if friend.first_name %}
                            <h6 class="mt-1">{{ friend.first_name }}({{ friend.email }})</h6>
                        {% else %}
                            <h6 class="mt-1">{{ friend.email }}</h6>
                        {% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        {% if not user in friends %}
            <a href="{% url 'album:change_friends' operation='add' pk=user.pk %}">
                <button type="button" class="btn btn-success">Add Friend</button>
            </a>
        {% else %}
        {% for friend in friends %}
            {% if user == friend %}
            <a href="{% url 'album:change_friends' operation='remove' pk=friend.pk %}">
                <button type="button" class="btn btn-danger">Remove Friend</button>
            </a>
            {% endif %}
        {% endfor %}
        {% endif %}
        {% if user != request.user %}
            <button onclick="window.location='{% url 'accounts:view_profile' %}'" class="btn btn-secondary my-2">My profile</button>
        {% endif %}
    {% endif %}
    <hr>
</div>
{% endblock %}