accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

    path('baby_profile/', views.baby_profile, name='baby_profile'),
    path('edit_baby_profile/edit/', views.edit_baby_profile, name='edit_baby_profile'),
]

album/urls.py
from django.urls import path
from . import views
from album.views import (
    PostDetailView,
    CalendarView,
    ImageDetailView,
)
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('test/', views.test, name='test'),

    path('like/<str:operation>/', views.like, name='like'),
    path('crop_upload/', views.crop_upload, name='crop_upload'),
    path('calendar/new/<str:date>/', views.calendar_new, name='calendar_new'),

    path('', login_required(CalendarView.as_view()), name='home'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),

    path('image/<int:post_pk>/<int:pk>/', login_required(ImageDetailView.as_view()), name='image_detail'),
    path('image/<int:pk>/edit/', views.image_edit, name='image_edit'),
    path('image/<str:operation>/<int:pk>/remove/', views.image_remove, name='image_remove'),
    path('image_comment/<int:pk>/remove/', views.image_comment_remove, name='image_comment_remove'),

    # notification
    path('notification/<str:operation>/<int:pk>/', views.notification, name='notification'),
    # friend
    path('connect/<str:operation>/<int:pk>/', views.change_friends, name='change_friends'),


    # Calendar album page
    path('calendar_view/', views.calendar_view, name='calendar_view'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
# from album.views import CalendarView

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('admin/', admin.site.urls),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('album/', include(('album.urls', 'album'), namespace='album')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager ## A new class is imported. ##
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _
from imagekit.models import ImageSpecField
from imagekit.processors import Resize

# Extending the base User manager that Django uses for its original UserManager.
class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    # Defining the same 3 methods that the original Django UserManager has.
    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

    # make first_name as case insenditive
    def filter(self, **kwargs):
        if 'first_name' in kwargs:
            kwargs['first_name__iexact'] = kwargs['first_name']
            del kwargs['first_name']
        return super(UserManager, self).filter(**kwargs)

    def get(self, **kwargs):
        if 'first_name' in kwargs:
            kwargs['first_name__iexact'] = kwargs['first_name']
            del kwargs['first_name']
        return super(UserManager, self).get(**kwargs)


# Extending the base class that Django has for User models.
class User(AbstractUser):
    """User model."""

    # Removing the username field.
    username = None
    # Making the email, first_name field required and unique.
    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), unique=True, max_length=20)

    # Telling Django that you are going to use the email field as the USERNAME_FIELD.
    USERNAME_FIELD = 'email'
    # Removing the email field from the REQUIRED_FIELDS settings (it is automatically included as USERNAME_FIELD).
    REQUIRED_FIELDS = []
    # Assigning the new Manager to the User model.
    objects = UserManager()


class UserProfileManager(models.Manager):
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset().filter(city='Sodra Sandby')


class UserProfile(models.Model):
    # From Django 2.0 on_delete is required
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    description = models.CharField(blank=True, max_length=100, default='')
    city = models.CharField(blank=True, max_length=100, default='')
    website = models.URLField(blank=True, default='')
    phone = models.CharField(blank=True, max_length=20, default='')
    image = models.ImageField(upload_to='profile_image', blank=True, default='profile_image/flower.png')
    image_thumbnail = ImageSpecField(
		source = 'image',
		processors = [Resize(700, 700)], # 처리할 작업 목룍
		format = 'JPEG',					# 최종 저장 포맷
		options = {'quality': 60})  		# 저장 옵션

    # Sodra_Sandby가 도시인 유저만 보이게 하고싶을때
    # Sodra_Sandby = UserProfileManager()
    objects = models.Manager()

    # user.userprofile 리턴값을 이름으로
    def __str__(self):
        return self.user.email

# User가 생성되면 UserProfile을 생성
def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=settings.AUTH_USER_MODEL)

class BabyProfile(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=20)
    born_weight = models.IntegerField(default=0)
    born_height = models.IntegerField(default=0)
    born_location = models.CharField(max_length=20, blank=True)
    birthday = models.DateTimeField()
    image = models.ImageField(upload_to='baby_profile_image', blank=True, default='profile_image/flower.png')
    image_thumbnail = ImageSpecField(
		source = 'image',
		processors = [Resize(700, 700)], # 처리할 작업 목룍
		format = 'JPEG',					# 최종 저장 포맷
		options = {'quality': 60})  		# 저장 옵션

    def __str__(self):
        return str(self.first_name)+str(self.last_name)

class Milestone(models.Model):
    milestone = models.CharField(max_length=30)
    date = models.DateField(null=True, blank=True)
    description = models.CharField(max_length=50)

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile, BabyProfile, Milestone
from accounts.models import User
from bootstrap_datepicker_plus import DatePickerInput, TimePickerInput

# class EntryForm(forms.Form):
#     name = forms.CharField(max_length=100)
#     date = forms.DateTimeField()
#     description = forms.CharField(widget=forms.Textarea)

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'email',
            'password1',
            'password2',
        )
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.is_active = False

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            'email',
            'password',
            'first_name',
            'last_name',
        )

class UserProfileImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = (
            'description',
            'city',
            'website',
            'phone',
            'image',
        )

class BabyForm(forms.ModelForm):
    birthday = forms.SplitDateTimeField()
    class Meta:
        model = BabyProfile
        fields = (
            'image',
            'first_name',
            'last_name',
            'birthday',
            'born_weight',
            'born_height',
            'born_location',
        )
    def __init__(self, *args, **kwargs):
        super(BabyForm, self).__init__(*args, **kwargs)
        self.fields['birthday'].widget.widgets[0]=DatePickerInput(format='%Y-%m-%d')
        self.fields['birthday'].widget.widgets[1]=TimePickerInput(format='%H:%M')

class MilestoneForm(forms.ModelForm):
    class Meta:
        model = Milestone
        fields = (
            'milestone',
            'date',
            'description',
        )

accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.http import HttpResponseRedirect
from django.contrib import messages
from accounts.models import User
from .models import UserProfile, BabyProfile
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from album.models import Calendar, Friend
from django.contrib.auth.decorators import login_required
from datetime import datetime
from .forms import (
    # EntryForm,
    RegistrationForm,
    EditProfileForm,
    UserProfileImageForm,
    BabyForm,
    MilestoneForm
)

def baby_profile(request):
    baby = BabyProfile.objects.get(first_name='Angelica Teresa Hyeyeong')
    today = datetime.now().date()

    posts = []
    newyear_post = Calendar.objects.filter(date__month='1', date__day='1').order_by('date').last()
    posts.append(newyear_post)

    christmas_post = Calendar.objects.filter(date__month='12', date__day='25').order_by('date').last()
    posts.append(christmas_post)

    if request.method == "POST":
        form = MilestoneForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            if 'image' in request.FILES:
                print('--------------milestone test-----------------')
            form.save()
            return redirect('accounts:baby_profile')
    else:
        form = MilestoneForm()

    args = {
        'baby': baby,
        'posts': posts,
        'today': today,
        'form': form,
    }
    return render(request, 'accounts/baby_profile.html', args)

@login_required
def edit_baby_profile(request):
    baby = get_object_or_404(BabyProfile, first_name='Angelica Teresa Hyeyeong')
    if request.user.is_superuser:
        if request.method == "POST":
            form = BabyForm(request.POST, instance=baby)
            if form.is_valid():
                baby = form.save(commit=False)
                if 'image' in request.FILES:
                    baby.image.delete()
                    baby.image = request.FILES['image']
                baby.save()
                return redirect('accounts:baby_profile')
        else:
            form = BabyForm(instance=baby)
        args = {
            'form': form,
        }
        return render(request, 'accounts/edit_baby_profile.html', args)
    else:
        return redirect('album:home')


def welcome(request):
    if request.method =='POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            ######### this makes users automatically log in when they successfully register
            # email = form.cleaned_data['email']
            # password = form.cleaned_data['password1']
            # user = authenticate(email=email, password=password)
            # login(request, user)
            ##########
            return redirect(reverse('accounts:login'))
    else:
        form = RegistrationForm()


    args = {'form': form}
    return render(request, 'welcome.html', args)

def user_login(request):
    if request.method == 'GET':
        context = ''
        return render(request, 'registration/login.html', {'context': context})

    elif request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        # setting.py -> AUTHENTICATION_BACKENDS -> allow inactive users to login
        user = authenticate(request, email=email, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('album:home'))
            else:
                context = 'Your account is not activated yet. Please contact Gwangyeong to activate your account.'  # to display error?
                return render(request, 'registration/login.html', {'context': context})
        else:
            context = 'Please enter a correct email and password. Note that both fields may be case-sensitive.'   # to display error?
            return render(request, 'registration/login.html', {'context': context})

@login_required
def view_profile(request, pk=None):
    if pk:
        user_pk = User.objects.get(pk=pk)
    else:
        user_pk = request.user

    users = User.objects.exclude(id=request.user.id)
    # friend = Friend.objects.get(current_user=request.user) => need to create
    friend, created = Friend.objects.get_or_create(current_user=request.user)
    friends = friend.users.all()

    args = {
        'user': user_pk,
        'users': users,
        'friends': friends,
    }
    return render(request, 'accounts/profile.html', args)

@login_required
def edit_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)

    if request.method == 'POST':
        edit_profile_form = EditProfileForm(request.POST, instance=request.user)
        user_profile_image_form = UserProfileImageForm(request.POST, request.FILES, instance=user_profile)

        if edit_profile_form.is_valid() and user_profile_image_form.is_valid():
            user = edit_profile_form.save()
            image = user_profile_image_form.save(commit=False)
            image.user = user

            if 'image' in request.FILES:

                image.image = request.FILES['image']

            image.save()
            return redirect(reverse('accounts:view_profile'))

        else:
            print(edit_profile_form.errors, user_profile_image_form.errors)
    else:
        edit_profile_form = EditProfileForm(instance=request.user)
        user_profile_image_form = UserProfileImageForm(instance=user_profile)

    args = {'edit_profile_form': edit_profile_form, 'user_profile_image_form': user_profile_image_form}
    return render(request, 'accounts/edit_profile.html', args)


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            messages.success(request, "Password has been successfully changed.")
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
    else:
        form = PasswordChangeForm(user=request.user)

    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)

accounts/templates/base.html
{% load static %}

<html>
    <head>
        <title>Hyeyeong's blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
        <!-- bootstrap Minty theme -->
        <link rel="stylesheet" href="{% static 'calendar/css/bootstrap.css' %}" />
        <!-- style.css -->
        <link rel="stylesheet" href="{% static 'calendar/css/style.css' %}" />
        <link rel="stylesheet" href="{% static 'calendar/css/bootstrap-datepicker.css' %}" />

        <!-- need to add to use bootstrap_datepicker_plus.. -->
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>

        {% block extrahead %}
        {% endblock %}
    </head>
    <body>
        <div class="view intro-base">
            <div class="full-bg-img spring-warmth-gradient">
                <div class="container">
                    <br>
                    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                        <a class="navbar-brand" href="{% url 'album:home' %}">Hyeyeong ♥</a>

                        <div class="collapse navbar-collapse" id="navbarColor02">
                            <ul class="navbar-nav mr-auto">
                                {% if user.is_superuser %}
                                <li class="nav-item active">
                                    <a class="nav-link" href="/admin">Admin <span class="sr-only">(current)</span></a>
                                </li>
                                {% endif %}

                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'accounts:view_profile' %}">My profile</a>
                                </li>
                                <li class="nav-item active">
                                    <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                                </li>
                            </ul>
                        </div>
                        <div class="">
                        {% if user.is_authenticated %}
                            <button onclick="window.location='{% url 'accounts:baby_profile' %}'" type="button" class="btn btn-secondary" data-toggle="popover" data-content="Hyeyeong's Profile" data-placement="bottom" data-container="body">
                                <i class="far fa-heart" style="font-size:20px;"></i>
                            </button>
                            <button onclick="window.location='{% url 'album:calendar_view' %}'" type="button" class="btn btn-secondary" data-toggle="popover" data-content="Calendar Album" data-placement="bottom" data-container="body">
                                <i class="far fa-calendar-alt" style="font-size:20px;"></i>
                            </button>
                            {% include 'album/notification.html' %}
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        {% endif %}
                        </div>
                    </nav>
                </div>

                <div class="container">
                    <div class="row">
                        <div class="col-sm-12">
                            <hr>
                            {% block content %}
                            {% endblock %}
                        </div>
                        <!-- <div class="col-sm-3">
                            {% block content_right %}
                            {% endblock %}
                        </div> -->
                    </div>
                </div>
            </div>
        </div>

        <!-- JQuery (Bootstrap보다 위에 넣어야함!!) -->
        <!-- <script type="text/javascript" src="{% static 'calendar/js/jquery-3.3.1.min.js' %}"></script> -->
        <!-- Tooltips -->
        <script type="text/javascript" src="{% static 'calendar/js/popper.min.js' %}"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="{% static 'calendar/js/bootstrap.min.js' %}"></script>
        <!-- MDB core JavaScript - Welcome page -->
        <script type="text/javascript" src="{% static 'calendar/js/mdb.min.js' %}"></script>

        <script type="text/javascript" src="{% static 'calendar/js/bootstrap-datepicker.js' %}"></script>


        <!-- Plugins -->
        <!-- Datepicker.js -->


        {% block script %}
        {% endblock %}


        <script type="text/javascript">
        $(function(){
            $('body').popover({
               selector: '[data-toggle="popover"]',
               trigger: 'hover',
               container:'body',
               animation:false
            }).on('hide.bs.popover', function () {
                if ($(".popover:hover").length) {
                  return false;
                }
            });

            $('body').on('mouseleave', '.popover', function(){
                $('.popover').popover('hide');
            });
        });
        </script>

        <!-- <script>
          var infinite = new Waypoint.Infinite({
            element: $('.infinite-container')[0],
            onBeforePageLoad: function () {
              $('.loading').show();
            },
            onAfterPageLoad: function ($items) {
              $('.loading').hide();
            }
          });
        </script> -->




    </body>
</html>

accounts/templates/index.html
{% extends 'first_page/base.html' %}

{% block content %}
<div class="page-center container">
    <h1>First Page!</h1>
    <p>Welcome to Hyeyeong's blog.</p>
    <button class="btn btn-success" onclick="window.location='{% url 'accounts:login' %}'">Login</button>
</div>
{% endblock %}