accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('login/', views.user_login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/<int:pk>/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),

    path('baby_profile/', views.baby_profile, name='baby_profile'),
    path('edit_baby_profile/edit/', views.edit_baby_profile, name='edit_baby_profile'),
]

album/urls.py
from django.urls import path
from . import views
from album.views import (
    PostDetailView,
    CalendarView,
    ImageDetailView,
)
from django.contrib.auth.decorators import login_required

urlpatterns = [

    path('test/', views.test, name='test'),

    path('like/<str:operation>/', views.like, name='like'),
    path('crop_upload/', views.crop_upload, name='crop_upload'),
    path('calendar/new/<str:date>/', views.calendar_new, name='calendar_new'),

    path('', login_required(CalendarView.as_view()), name='home'),
    path('post/<int:pk>/', login_required(PostDetailView.as_view()), name='post_detail'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('post/<int:pk>/remove/', views.post_remove, name='post_remove'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),

    path('image/<int:post_pk>/<int:pk>/', login_required(ImageDetailView.as_view()), name='image_detail'),
    path('image/<int:pk>/edit/', views.image_edit, name='image_edit'),
    path('image/<str:operation>/<int:pk>/remove/', views.image_remove, name='image_remove'),
    path('image_comment/<int:pk>/remove/', views.image_comment_remove, name='image_comment_remove'),

    # notification
    path('notification/<str:operation>/<int:pk>/', views.notification, name='notification'),
    # friend
    path('connect/<str:operation>/<int:pk>/', views.change_friends, name='change_friends'),


    # Calendar album page
    path('calendar_view/', views.calendar_view, name='calendar_view'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views
# from album.views import CalendarView

urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('admin/', admin.site.urls),
    path('account/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('album/', include(('album.urls', 'album'), namespace='album')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

album/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from multiselectfield import MultiSelectField
from django_resized import ResizedImageField

EMOTICONS = (
    ('happy', 'Happy'),
    ('sleepy', 'Sleepy'),
    ('sick', 'Sick'),
    ('angry', 'Angry'),
    ('bored', 'Bored'),
    ('laugh', 'Laugh'),
    ('love', 'Love'),
    ('pout', 'Pout'),
    ('sad', 'Sad'),
)

# Create your models here.
class Calendar(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.TextField()
    date = models.DateField()
    emoticon = MultiSelectField(choices=EMOTICONS, max_choices=3)
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='likes')

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

# Calendar comment
class Comment(models.Model):
    post = models.ForeignKey('album.Calendar', related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # author = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.post) + str(self.comment)

# Calendar images
class Image(models.Model):
    post = models.ForeignKey('album.Calendar', related_name='images', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    image = ResizedImageField(size=[1600, 1200], upload_to='calendar_image/%Y/%m')
    thumbnail = ImageSpecField(
		source = 'image',
		processors = [ResizeToFill(700, 700)], # 처리할 작업 목룍
		format = 'JPEG',					# 최종 저장 포맷
		options = {'quality': 60})  		# 저장 옵션
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='image_likes')

    def __str__(self):
        return str(self.pk)+', '+str(self.post.title)+'\'s image'

    def total_likes(self):
        return self.likes.count()


# Calendar comment
class ImageComment(models.Model):
    image = models.ForeignKey('album.Image', related_name='image_comments', on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # author = models.CharField(max_length=100)
    comment = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='image_replies', on_delete=models.CASCADE)

    def __str__(self):
        return str(self.image) + str(self.comment)

class Friend(models.Model):
    # related_name의 default는 related_name='friend_set'이므로 중복되지 않도록  이름을 지어준것
    users = models.ManyToManyField(settings.AUTH_USER_MODEL)
    current_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='owner', null=True, on_delete=models.CASCADE)

    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.add(new_friend)

    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(
            current_user = current_user
        )
        friend.users.remove(new_friend)

class Notification(models.Model):
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sender', on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='receiver', on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    read = models.BooleanField(default=False)
    post = models.ForeignKey('album.Calendar', related_name='post_notification', blank=True, null=True, on_delete=models.CASCADE)
    post_comment =  models.ForeignKey('album.Comment', related_name='post_comments_notification', blank=True, null=True, on_delete=models.CASCADE)
    image = models.ForeignKey('album.Image', related_name='image_notification', blank=True, null=True, on_delete=models.CASCADE)
    image_comment = models.ForeignKey('album.ImageComment', related_name='image_comments_notification', blank=True, null=True, on_delete=models.CASCADE)
    like = models.BooleanField(default=False)

    def __str__(self):
        try:
            output = 'parent='+str(self.image_comment.parent.id)+'. '+str(self.sender.first_name)+' -> '+str(self.receiver.first_name)+':'+str(self.image_comment.comment)
        except:
            output = str(self.sender.first_name) + ' -> ' + str(self.receiver.first_name)

        return output


class YunList(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_date = models.DateTimeField(default=timezone.now)
    check = models.BooleanField(default=False)
    content = models.CharField(max_length=200, blank=True)
    comment = models.ForeignKey('self', null=True, blank=True, related_name='comments', on_delete=models.CASCADE)
    reply = models.ForeignKey('self', null=True, blank=True, related_name='replies', on_delete=models.CASCADE)

album/forms.py
from django import forms
from .models import Calendar, Comment, Image, ImageComment
from bootstrap_datepicker_plus import DatePickerInput

class CalendarForm(forms.ModelForm):

    class Meta:
        model = Calendar
        fields = (
            'title',
            'description',
            'date',
            'emoticon'
        )
        widgets = {
            'date': DatePickerInput(format='%Y-%m-%d')
        }

class CommentForm(forms.ModelForm):
    # comment = forms.CharField(widget=forms.TextInput(
    #     attrs={
    #         'class': 'form-control',
    #         'placeholder': "Write a comment..."
    #     }
    # ))
    class Meta:
        model = Comment
        fields = ('comment',)



class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = (
            'description',
            'image',
        )

class ImageCommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': "Write a comment..."
        }
    ))
    class Meta:
        model = ImageComment
        fields = ('comment',)

album/templates/album/home.html
{% extends 'base.html' %}

{% block content %}
<div class="row mb-0 mt-4">
    <div class="col-sm-6">
        <h5 class="font-weight-bold">
            Welcome,
            <a class="text-info" href="{% url 'accounts:view_profile' %}">
            {{user.first_name}}!
            </a>
        </h5>
    </div>
    <div class="col-sm-6">
        <button class="btn btn-primary float-right" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Search
        </button>
    </div>
</div>

<!-- Search collapse -->
<div class="collapse" id="collapseExample">
<hr>
  <div class="card card-body">
      <form class="" method="get">
          <div class="form-inline my-2">
              <input class="form-control my-2 col-6" placeholder="Date" type="text" id="datepicker" name="year_month">
              <select class="form-control my-2 col-6" name="emoticon">
                  <option selected value="" >Emoticon</option>
                  {% for value, text in form.emoticon.field.choices %}
                      <option value="{{value}}">{{text}}</option>
                  {% endfor %}
              </select>
          </div>

          <div class="input-group mb-3">
              <div class="input-group-prepend">
                  <select class="btn btn-secondary" name="option">
                      <option value="title">Title</option>
                      <option value="content">Content</option>
                  </select>
              </div>
              <input class="form-control" placeholder="Search..." type="text" name="search_content" maxlength="15">
          </div>
          <button type="submit" class="btn btn-primary float-right">Search</button>
      </form>
  </div>
</div>

<hr>

<!-- msg from views/post_new when you try to post on the date that has a post already -->
{% if msg %}
    <p id="msg">{{msg}}</p>
    <a class="btn btn-primary btn-sm" href="{% url 'album:post_detail' pk=post.pk %}">Open Post</a>
    {% if post.author == user %}
        <a class="btn btn-secondary btn-sm" href="{% url 'album:post_edit' pk=post.pk %}">Edit Post</a>
    {% endif %}
{% endif %}

<h2 class="my-4 text-center">
    <form class="my-2 mr-2" action="" method="get">
        {% if emoticon or search_content %}
            Search Results <br>
            [
            {% if year_month %}
                {{ year_month|date:"Y. m" }} /
            {% endif %}
            {% if emoticon %}
                <img src="/media/emoticons/{{ emoticon }}.png" style="width:30;">
            {% endif %}
            {% if emoticon and search_content %}
            /
            {% endif %}
            {% if search_content %}
                {{option|title}} : {{search_content}}
            {% endif %}
            ]
        {% elif year_month %}
        <button type="submit" class="btn btn-primary mr-sm-5" name="year_month"  value="{{pre_year_month}}">Back</button>
        {{ year_month|date:"Y. m" }}
        <button type="submit" class="btn btn-primary ml-sm-5" name="year_month"  value="{{next_year_month}}">Next</button>
        {% endif %}
    </form>
</h2>

<div class="container">
    <div class="row text-center">
        {% for post in posts %}
        <div class="card text-center mb-3 col-6 col-lg-4">
            <h3 class="card-header home_year_month">{{ post.date|date:"Y.m.d" }}</h3>

            <div class="pt-1 pr-1">
                <span class="like_button float-right">
                <a class="like" name="{{ post.id }}" value="Like">
                    {% if user in post.likes.all %}
                        <button class="btn btn-secondary" type="button" name="button">
                            <i class="fas fa-heart" id="heart{{post.id}}" style="color: red;"></i>
                        </button>
                        </a>
                    {% else %}
                        <button class="btn btn-secondary" type="button" name="button">
                            <i class="far fa-heart" id="heart{{post.id}}" style="color: red;"></i>
                        </button>
                        </a>
                    {% endif %}
                </span>
            </div>


            <a class="portfolio-box" href="{% url 'album:post_detail' pk=post.pk %}">
                {% for thumb in post.images.all %}
                    {% if forloop.counter == 1 %}
                    <img class="img-thumbnail w3-round-xlarge img-responsive" style="width: 100%; display: block;" src="{{ thumb.thumbnail.url }}" alt="Card image">
                    {% endif %}
                {% endfor %}
                <div class="portfolio-box-caption">
                    <div class="portfolio-box-caption-content">
                        <div class="project-category text-faded">
                            title
                        </div>
                        <div class="project-name">
                            {{ post.title }}
                        </div>
                        <!-- <hr>
                            {% with total=post.comments.count %}
                                {{ total }} comment{{ total|pluralize }}
                            {% endwith %}

                            {% for image in post.images.all %}
                                {{ forloop.counter }}. {{ image.image_comments.count }}<br>
                            {% endfor %} -->
                    </div>
                </div>
            </a>
            <form method="get" class="form-inline">
                <div class="row justify-content-center">
                    {% for emot in post.emoticon %}
                    <div class="col-4" style="padding: 4%;">
                        <button type="submit" class="btn btn-outline-primary btn-sm" name="emoticon" value="{{ emot }}" style="padding: 0.1rem 0.1rem; border-color: transparent;">
                            <img src="/media/emoticons/{{ emot }}.png" style="width: 100%; display: block;">
                        </button>
                    </div>
                    {% endfor %}
                </div>
            </form>

        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block script %}
<script type="text/javascript">
    $(function() {
        $('#datepicker').datepicker({
            minViewMode: 1,
            format: 'yyyy-mm',
            autoclose: true,
            todayHighlight: true,
        });
    });
</script>

<script type="text/javascript">
    // 좋아요 버튼 처리
    // 버튼 클릭 > ajax통신 (like url로 전달) > views의 like 메소드에서 리턴하는 값 전달받기 > 성공시 콜백 호출
    $('.like').click(function() {
        var pk = $(this).attr('name') // 클릭한 요소의 attribute 중 name의 값을 가져온다.
        $.ajax({
            type: "POST", // 데이터를 전송하는 방법을 지정한다.
            url: "{% url 'album:like' operation='post' %}", // 통신할 url을 지정한다.
            data: {
                'pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            }, // 서버로 데이터를 전송할 때 이 옵션을 사용한다.
            dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정한다. 없으면 알아서 판단한다.

            success: function(response) { // 성공했을 때 호출할 콜백을 지정한다.
                id = $(this).attr('name')
                if (response.user_like) {
                    $('#heart' + pk).removeClass('far fa-heart').addClass('fas fa-heart');
                }
                else {
                    $('#heart' + pk).removeClass('fas fa-heart').addClass('far fa-heart');
                }

                // alert(response.message);
                // alert("Total likes : " + response.likes_count);
            },
            error: function(request, status, error) {
                alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
            }
        });
    })
    // alert if msg exists from views/post_new
    var msg = document.getElementById('msg');
    if (msg) {
        alert('Post exists on selected date.')
    }
</script>

{% endblock %}

album/templates/album/image_edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Edit image</h1>

<form method="post" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}

    Current picture : {{ form.image.value }}
    <br>
    <label>Picture</label>
    <div class="custom-file">
        <input id="fileupload" type="file" name="image" value="{{ form.image.value }}" multiple onchange="javascript:updateList()" class="custom-file-input" accept="image/*">
        <label class="custom-file-label" for="inputGroupFile02">Change Picture</label>
    </div>
    <div id="fileList">

    </div>


    <br>
    <label>{{ form.description.label }}</label>
        <input placeholder="{{ form.description.label }}" value="{{ form.description.value }}" name="description" class="form-control">

    <hr>
    <button type="submit" name="button" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

{% block script %}
<!-- Displays selected files -->
<script type="text/javascript">
updateList = function() {
    var input = document.getElementById('fileupload');
    var output = document.getElementById('fileList');

    htmlStr = 'Selected files:<ul>';
    for (var i = 0; i < input.files.length; ++i) {
        htmlStr += '<li>' + input.files.item(i).name + '</li>';
    }
    htmlStr += '</ul>';
    output.innerHTML = htmlStr
}
</script>

<script type="text/javascript">
        $(function () {
            $('#datepicker').datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight : true,
            });
        });
</script>
{% endblock %}

album/templates/album/post_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="post">
        {% if user.is_authenticated and user.is_superuser or user == post.author %}
        <!-- 수정버튼 -->
        <a class="btn btn-secondary btn-sm" href="{% url 'album:post_edit' pk=post.pk %}">Edit</a>

        <!-- 삭제버튼 -->
        <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#delete_image">Delete</button>
        <!-- delete Modal -->
        <div class="modal fade" id="delete_image" tabindex="-1" role="dialog" aria-labelledby="delete_imageLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="delete_imageLabel">Delete Picture</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        All pictures in this post will be deleted as well.<br>
                        Are you sure you want to delete this post?
                    </div>
                    <div class="modal-footer">
                        <a class="btn btn-primary btn-sm" href="{% url 'album:post_remove' pk=post.pk %}">Yes, Delete</a>
                        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">No, Cancel</button>
                    </div>
                </div>
            </div>
        </div>


        <a class="btn btn-primary btn-sm" href="{% url 'album:post_detail' pk=previous_post.pk %}">Prev Day</a>
        <a class="btn btn-primary btn-sm" href="{% url 'album:post_detail' pk=next_post.pk %}">Next Day</a>
        {% endif %}
        <hr>

        <h1>Title : {{ post.title }}</h1>
        <h2>{{ post.date|date:"Y.m.d" }}</h2>
        <p>description : {{ post.description }}</p>
        {% if post.author.first_name %}
        <p>Posted by {{ post.author.first_name }}</p>
        {% else %}
        <p>Posted by {{ post.author }}</p>
        {% endif %}

        <div id="carouselExampleControls" class="carousel slide col-lg-7 " data-ride="carousel">
            <ol class="carousel-indicators">
                {% if post.images.all|length > 1 %}
                    {% for image in post.images.all %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter0}}" class="{% if forloop.counter0 == 0 %}active{% endif %}"></li>
                    {% endfor %}
                {% endif %}
            </ol>

            <div class="carousel-inner">
                {% for image in post.images.all %}
                    <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %}">
                        <a class="portfolio-box" href="{% url 'album:image_detail' post_pk=post.pk pk=image.pk  %}">
                            <img class="img-thumbnail" src="{{ image.thumbnail.url }}" alt="First slide">
                            <div class="portfolio-box-caption">
                                <div class="portfolio-box-caption-content">
                                    {% if image.description %}
                                        <div class="project-category text-faded">
                                            description
                                        </div>
                                        <div class="project-name">
                                            <h2>{{ image.description }}</h2>
                                        </div>
                                    {% endif %}
                                    {% with total=image.image_comments.count %}
                                        {{ total }} comment{{ total|pluralize }}
                                    {% endwith %}
                                </div>
                            </div>
                        </a>
                    </div>
                    {% if post.images.all|length != 1 %}
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>

    <br>
    <hr>

    <span class="like_button float-right">
        <a class="like" name="{{ post.id }}" value="Like">
            <button class="btn btn-secondary" type="button" name="button">
            {% if user in post.likes.all %}
                <i class="fas fa-heart" id="heart" style="color: red;"></i>
            {% else %}
                <i class="far fa-heart" id="heart" style="color: red;"></i>
            {% endif %}
            </button>
        </a>
        <a tabindex="0" class="badge badge-primary badge-pill" id="count{{post.id}}" data-toggle="popover" title="People who like this post." data-placement="top"
            data-content="
            {% for user in post.likes.all %}
                {{user}}
            {% endfor %}
            ">{{ post.total_likes }}
        </a>
    </span>

    <a class="btn btn-primary" data-toggle="collapse" href="#comment_collapse" role="button" aria-expanded="false" aria-controls="collapseExample">
        Comment
    </a>
    <div class="collapse" id="comment_collapse">
        <hr>
        {% if user.is_authenticated %}
            <form method="post" autocomplete="off">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" name="comment" maxlength="200" required id="id_comment" class="form-control" placeholder="Write a comment..." aria-describedby="button-addon2">
                    <div class="input-group-append">
                        <button class="btn btn-primary" type="submit" id="button-addon2">Add Comment</button>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
    <hr>

    {% for comment in comments %}
    <div class="media pb-2">
        {% for user in users %}
            {% if user == comment.author %}
                <a href="{{ user.userprofile.image.url }}">
                    <img class="rounded-circle mr-3" src="{{ user.userprofile.image_thumbnail.url }}" width="62" height="62"/>
                </a>
                <div class="media-body">
                    <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                        {% if user.first_name %}
                            <h5 class="mt-0 font-weight-bold">{{ user.first_name }}</h5>
                        {% else %}
                            <h5 class="mt-0 font-weight-bold">{{ comment.author }}</h5>
                        {% endif %}
                    </a>
                    <h5>{{ comment.comment }}</h5>
                </div>
            {% endif %}
        {% endfor %}
        {% if user.is_superuser or user == comment.author %}
            <a class="btn-sm text-danger" href="{% url 'album:comment_remove' pk=comment.pk %}">Delete</a>
        {% endif %}
    </div>

    {% for reply in comment.replies.all %}
        <div class="media pl-5 pb-2">
            {% for user in users %}
                {% if user == reply.author %}
                    <a href="{{ user.userprofile.image.url }}">
                        <img class="rounded-circle mr-3" src="{{ user.userprofile.image_thumbnail.url }}" width="40" height="40"/>
                    </a>
                    <div class="media-body">
                        <a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
                            {% if user.first_name %}
                                <h6 class="mt-0 font-weight-bold">{{ user.first_name }}</h6>
                            {% else %}
                                <h6 class="mt-0 font-weight-bold">{{ reply.author }}</h6>
                            {% endif %}
                        </a>
                        <h6>{{ reply.comment }}</h6>
                    </div>
                {% endif %}
            {% endfor %}
            {% if user.is_superuser or user == reply.author %}
                <a class="btn-sm text-danger" href="{% url 'album:comment_remove' pk=reply.pk %}">Delete</a>
            {% endif %}
        </div>
    {% endfor %}

    <a class="btn btn-primary btn-sm" data-toggle="collapse" href="#reply_collapse{{forloop.counter}}" role="button" aria-expanded="false" aria-controls="collapseExample">
        Reply
    </a>
    <div class="collapse" id="reply_collapse{{forloop.counter}}">
        <hr>
        <form action="." method="post" autocomplete="off">
            {% csrf_token %}
            {{ form.errors }}
            <!-- Hidden input for parent comment.id -->
            <div class="input-group mb-3 pl-5">
                <input type="text" name="comment" maxlength="200" required id="id_comment" class="form-control" placeholder="Write a reply..." aria-describedby="button-addon2">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="submit" id="button-addon2">Reply</button>
                </div>
            </div>
            <input type="hidden" name="parent_id" value="{{ comment.id }}">
        </form>
    </div>

    <hr>

    {% if forloop.last %}
        <br><br><br>
    {% endif %}

    {% empty %}
    <p>No comments here yet...</p>
    <br><br><br>
    {% endfor %}

{% endblock %}

{% block script %}
<script type="text/javascript">
    // 좋아요 버튼 처리
    // 버튼 클릭 > ajax통신 (like url로 전달) > views의 like 메소드에서 리턴하는 값 전달받기 > 성공시 콜백 호출
    $('.like').click(function() {
        var pk = $(this).attr('name') // 클릭한 요소의 attribute 중 name의 값을 가져온다.
        $.ajax({
            type: "POST", // 데이터를 전송하는 방법을 지정한다.
            url: "{% url 'album:like' operation='post' %}", // 통신할 url을 지정한다.
            data: {
                'pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}'
            }, // 서버로 데이터를 전송할 때 이 옵션을 사용한다.
            dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정한다. 없으면 알아서 판단한다.

            success: function(response) { // 성공했을 때 호출할 콜백을 지정한다.
                id = $(this).attr('name')
                $('#count' + pk).html(response.likes_count);
                if (response.user_like) {
                    $('#heart').removeClass('far fa-heart').addClass('fas fa-heart');
                } else {
                    $('#heart').removeClass('fas fa-heart').addClass('far fa-heart');
                }

                // alert(response.message);
                // alert("Total likes : " + response.likes_count);
            },
            error: function(request, status, error) {
                alert("code:" + request.status + "\n" + "message:" + request.responseText + "\n" + "error:" + error);
            }
        });
    })
</script>
{% endblock %}